### ISSUE TITLE
Separate plots from computations

### ISSUE THREAD

**Issue by mstaniak** [StatsIMUWr/SpotifyViz#1]

**Comment by mstaniak** [comment]
+ group functions logically, for example counts but weekday/hour/month are the same calculation/plot, just with a different time period

**Comment by mabuszka** [comment]
So we should make a function that is filtering the data table and another that just makes a plot, and just add a parameter "period of time" to the functions?

**Comment by mstaniak** [comment]
Absolutely. For plotting functions, plot types are most important - particular aesthetics can be passed as parameters to `aes_string` (plotting function only needs to know that it's supposed to make a, say, dot plot, no need to know the time period on x axis). Functions that compute some statistics should output a `data.table`.

**Comment by mabuszka** [comment]
Thanks for the `aes_string` hint, I didn't know about it. I will try to change the functions.
